# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://headspringlabs.com
title: Headspring Labs
subtitle: Experiments by Headspringers!
author: Headspring Labs
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: HeadspringLabs
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: HeadspringLabs
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true

# ----------------------- #
#    Author Information   #
# ----------------------- #
authors:
  alonso:
    name: Alonso Robles
    gravatar: 95a087322938a69b9670c28291e4f479
    twitter: alonsorobles
    github: alonsorobles
  anne:
    name: Anne Epstein
    gravatar: 18d71aac83cd382ef818ea8480091546
    twitter: ajepst
    github: ajepst
  cedric:
    name: Cedric Yao
    gravatar: 38e93c75af646c8b4032737b202c551c
    twitter: raspar
    github: cedricyao
  chris:
    name: Chris Missal
    gravatar: 09f73b6f180bb61f39369784d5082d09
    twitter: ChrisMissal
    github: ChrisMissal
  deran:
    name: Deran Schilling
    gravatar: f7f5ab2e221884860465b7b1b3e8b510
    twitter: derans
    github: derans
  jimmy:
    name: Jimmy Bogard
    gravatar: 462cca297af6670cf47aaf5551740f12
    twitter: jbogard
    github: jbogard
  justinm:
    name: Justin Mason
    gravatar: 8da49f2d2ef715b9c0286d16ead63da1
    twitter: 
    github: 
  justin:
    name: Justin Pope
    gravatar: 52adb727732c916e9bbc756f33817d48
    twitter: 
    github: 
  kevin:
    name: Kevin Hurwitz
    gravatar: 556e1c922da51113ba0fe95ec5314a1b
    twitter: 
    github: 
  kurt:
    name: Kurt Schindler
    gravatar: 8e2b5e14b06394846485f4ccd92f7669
    twitter: kurtschindler
    github: kurtschindler
    former: true
  kyle:
    name: Kyle Nunery
    gravatar: 29a6abc71855afdb60312a6013772834
    twitter: knunery
    github: knunery
  logan:
    name: Logan Turner
    gravatar: f5203a0532598243c6cc04296a19491e
    twitter: _loganturner
    github: loganturner
  mahendra:
    name: Mahendra Mavani
    gravatar: 5b7c10a7fe37184b3e85187858b68cff
    twitter: mahendramavani
    github: mahendramavani
  nolan:
    name: Nolan Egly
    gravatar: bd9b5f1fa3e3da40260b9124a6fa3178
    twitter: nolanegly
    github: nolanegly
  patrick:
    name: Patrick Lioi
    gravatar: 132b05329f7c2dfa5fc9d04c4ab22ce3
    twitter: plioi
    github: plioi
  sharon:
    name: Sharon Cichelli
    gravatar: 24e4848cfb6d2508ecebee4ad8ef1c47
    twitter: scichelli
    github: scichelli
  tim:
    name: Tim G. Thomas
    gravatar: 9941404190648abe46e52c4b07bd6caf
    twitter: timgthomas
    github: timgthomas
